language: ruby
cache:
  bundler: true
  apt: true
  directories:
  - build
  - node_modules
before_install: nvm install v5.11.1
install: bundle install --jobs=3 --retry=3 && npm install
script: bundle exec rake deploy
branches:
  only:
  - master
notifications:
  slack:
    secure: lESWggseejuz+Z4PdTGpUBSwOsnB8jRwzUkRITTLzmLJ83My3g238hZZtdP6C1BnwtgFHQ89X1hl8jcBhfdeh6YxGZEccopCNd6d8BWnpgq7SVSHSQEF7A8HJGRPhJjj7xCf/ts2HKH0PyphHULJMV4/Khd5n96AMjZIwWcvsP2mXW/dhgzfe3vMN2Cc5x3UxZfUdii5REXxX8dmunKOWCxccq+nWuWY0X4pdY6RSIJapDrjWgkfRHgAhY3ANmLAgBI6mrY9cL3eCwNFER4tvoL7IMGtTOeSa8NDv74v3nvUjGLcGSK3fn7JEgXSeGfb9M8Yp6p04tu7HCdnDcgqbo3MrO0UIIUljOooYxX6hPhuo6cvn/xtvFuud/7WKnDcsJ7oTMjrFpTZ80o11J9KOiI433rKDrj4eTIXfWj2k14aj0tPYf6eZ5Hyhpq2Es6Wmqg8cURWwLAOU9OMVtQhQQGs/dxZHWuwEmb0Vr9D4L4dkkynGVeJ61wyE4mgfda8HJhKfHUq3KMTyYh+C54kdF6iccT9ImYp7SX1ekTN2kP1UbIf1CtGDpfMzbSr3oNLe+verMs4Cy6BwcAsrAneKgl+RZaqvYOso6dt682/daHlLY4Svdeg0Bzmkn+MwzZrthfA42sIDDf01FojSqF+cYiTmB2dtsiw2YDdwwvJVog=
